name: canopy-app
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.7
  #
  # Core
  - f90nml
  - netcdf4
  - numpy
  - pandas
  - xarray
  #
  # Examples
  - cartopy
  - ipympl
  - ipywidgets
  - jupyterlab
  - matplotlib
  #
  # Extra
  - ipython
  - pysolar
  - scipy
