name: CI

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [gfortran-9, gfortran-10, gfortran-11]

    steps:
      - uses: actions/checkout@v3

      - name: Debug compile and run
        run: |
          make clean
          DEBUG=1 make
          ./canopy

      - name: Non-debug compile and run
        run: |
          make clean
          DEBUG=0 make
          ./canopy
